### PR TITLE
Fix debugger launch failure with spaces in interpreter path (regression from #964)

### LINKED ISSUE #1013: Latest release version of the debugger will not start the debugging process
The debugging process is not starting when Run/Start Debugging is clicked.

VS Code version:
Version: 1.117.0 (user setup)
Commit: 10c8e557c8b9f9ed0a87f61f1c9a44bde731c409
Date: 2026-04-21T16:12:14-07:00
Electron: 39.8.7
ElectronBuildId: 13841579
Chromium: 142.0.7444.265
Node.js: 22.22.1
V8: 14.2.231.22-electron.0
OS: Windows_NT x64 10.0.26200

Python Debugger extension version: ms-python.debugpy 2026.4.0

The only workaround I found is to change "type": "debugpy" to "type": "python".

### PR DESCRIPTION
**Pull request by ZA139**
### Problem
The debugger fails to start (ENOENT error) when the Python interpreter path contains spaces, such as `C:\Program Files\Python312\python.exe`. This is a regression introduced in version 2026.4.0.

### Root Cause
PR #964 unconditionally applied shell-style quoting via `fileToCommandArgumentForPythonExt()` to wrap the interpreter executable path before passing it to `DebugAdapterExecutable`. 

However, `DebugAdapterExecutable` internally uses `child_process.spawn()` in a **non-shell environment**. In this mode:
- Literal quote characters are treated as **part of the filename** rather than delimiters
- This causes the OS to look for a file literally named `"C:\...\python.exe"` (including the quotes)
- Result: `ENOENT: file not found`

### Solution
Remove the shell-style quoting step for the executable path. `child_process.spawn()` correctly handles spaces in paths via array-based argument passing and does not require manual quoting.

### Changes
1. **factory.ts**: Remove `fileToCommandArgumentForPythonExt(executable)` call and replace with explanatory comment
2. **factory.unit.test.ts**: Update two test cases to expect unquoted paths instead of quoted paths

### Testing
- Both "interpreter path with spaces" test cases now verify that paths are passed **without** quotes
- The tests cover both default adapter path and custom debugAdapterPath scenarios

### Related Issues
- Fixes #1013
- Regression from #964

### CODE REVIEW

File: src/extension/debugger/adapter/factory.ts [hunk 1]
```diff
@@ -79,13 +78,12 @@ export class DebugAdapterDescriptorFactory implements IDebugAdapterDescriptorFac
...
-
-            // Always ensure interpreter/command is quoted if necessary. Previously this was
-            // only done in the debugAdapterPath branch which meant that in the common case
-            // (using the built‑in adapter path) an interpreter path containing spaces would
-            // be passed unquoted, resulting in a fork/spawn failure on Windows. See bug
-            // report for details.
-            executable = fileToCommandArgumentForPythonExt(executable);
+            // DO NOT apply shell-style quoting here.
+            // The 'executable' path is passed to 'DebugAdapterExecutable', which internally
+            // uses 'child_process.spawn' in a non-shell environment.
```
Comment (rchiodo) [inline src/extension/debugger/adapter/factory.ts:83]: Isn't this breaking the original fix in a shell environment? Seems like fileToCommandArgumentForPythonExt should have some way of checking how the launch is going to happen.

Comment (ZA139) [reply src/extension/debugger/adapter/factory.ts:83]: > Isn't this breaking the original fix in a shell environment? Seems like fileToCommandArgumentForPythonExt should have some way of checking how the launch is going to happen.

Yep, totally agreed — simply removing `fileToCommandArgumentForPythonExt` is not sufficient.  
The correct fix should depend on whether `spawn` is running in a shell environment:  

- If `options.shell === true`, we need quotes to handle spaces correctly.  
- If `options.shell === false` (default), we must avoid quotes to prevent ENOENT.  

So instead of removing the helper entirely, we should update `fileToCommandArgumentForPythonExt` to accept a `isShell` flag and return the path accordingly.

Comment (rchiodo) [reply src/extension/debugger/adapter/factory.ts:83]: I'm not sure if it's a shell environment. It's just whether or not this command is a bat/cmd file.
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/node/debugAdapter.ts#L173-L180

So maybe this is the correct fix.

**Review by rchiodo — APPROVED** [review]

**Review by edvilme — APPROVED** [review]

**Comment by rchiodo** [comment]
@ZA139 can you update the branch? Otherwise I need to get two other people to sign off (well because I'll count as a contributor). 

I've tested the fix locally with and without arguments and it works good.

**Review by bschnurr — APPROVED** [review]

**Comment by rchiodo** [comment]
Okay nevermind, just merged it. Thanks @ZA139 for the fix.

**Comment by ZA139** [comment]
> Okay nevermind, just merged it. Thanks @ZA139 for the fix.

@rchiodo Sorry about the delay — that was 4am in my time zone. I'll enable auto-merge next time.

For context: I converted the PR to draft after submitting because the unit test suite passed cleanly, but every F5 / launch scenario I tried against my locally-built VSIX failed last night. If the same F5 scenarios work on your end, that's almost certainly an issue with my local build environment. 
Since one of my PRs went out in this release, I was watching the incoming issues afterwards and noticed this one. I had already confirmed the root cause with a minimal Node `child_process.spawn` repro that reproduced the ENOENT from the literally-quoted path, so for the sake of a quick fix I went ahead and sent the PR before finishing the full local VSIX test pass — apologies for the shortcut.

AnyWay, glad I could help, and thanks for the quick reviews.

**Comment by rchiodo** [comment]
Oh maybe we should wait to ship until you test it. I tested it locally and it works fine. Both with and without spaces in the path to the python executable. 
[ms-python.debugpy.2026.6.0.win32-x64.zip](https://github.com/user-attachments/files/27250187/ms-python.debugpy.2026.6.0.win32-x64.zip)
That's the vsix renamed to zip form. If anybody else can try it out, that'd be great.

**Comment by ZA139** [comment]
> Oh maybe we should wait to ship until you test it. I tested it locally and it works fine. Both with and without spaces in the path to the python executable. [ms-python.debugpy.2026.6.0.win32-x64.zip](https://github.com/user-attachments/files/27250187/ms-python.debugpy.2026.6.0.win32-x64.zip) That's the vsix renamed to zip form. If anybody else can try it out, that'd be great.

@rchiodo Confirmed. This vsix works well in my local environment. Both with and without spaces in the path to the python executable. BTW, maybe shipping a pre-release version is an option. After shipping, we can seek #1013 users for a second check.

**Comment by rchiodo** [comment]
Thanks for confirming. I'm just going to release. This is a pretty bad regression.

**Comment by ZA139** [comment]
> Thanks for confirming. I'm just going to release. This is a pretty bad regression.

Makes sense. I’ll keep an eye on issue #1013 to see if any edge cases pop up after the update.
Thanks for the quick turnaround on this!
